version: '3'

services:

  oak:
    build: .    
    image: oak:devel
    restart: on-failure
    container_name: oak_container
    command: python main.py
    env_file: ak_env
    volumes:
      - .:/app
      - static_data:/app/static

volumes:
  static_data:
